### ISSUE TITLE
Bad url hash

### ISSUE THREAD

**Issue by mahadshahib** [parthpower/loonabot#7]
hi in new instagram ?__a=1 response all urls in imageversion2 and video version return bad url hash and cant get downloaded what is the problem?

**Comment by parthpower** [comment]
Haven't seen this issue. Can you share a response json from `?__a=1` that reproduces the issue?

**Comment by mahadshahib** [comment]
Well i fixed it , but apparently if you call api on browser and copy url from json appears on screen you will get 403 forbidden from instagram but if you call it on code , or postman for example you should be ok
> Haven't seen this issue. Can you share a response json from `?__a=1` that reproduces the issue?

**Comment by parthpower** [comment]
Might have something to with the browser cookies. I have been using Firefox (96.0.3) and image urls seems to work fine. Please reopen if you see this issue on the `pkg/insta` library.
